from . import auto_info_brtihday
from . import adminpost
from . import birthday_handlers
from . import help
from . import infoBirthday
from . import sozlamalar
from . import support
from . import start
from . import fr_auot_info